version: '3'

services: 
    item-api:
        image: meaty/itemservice
        container_name: itemapi
        restart: always
        build:
            context: ./itemservice
            dockerfile: Dockerfile
        environment: 
            - DSN=host=postgres user=admin password=pass dbname=itemcatalog port=5432 sslmode=disable
        ports: 
            - "8080:8080"
        depends_on: 
            - postgres
    postgres:
        image: postgres:latest
        restart: always
        environment: 
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - APP_DB_USER=admin
            - APP_DB_PASS=pass 
            - APP_DB_NAME=itemcatalog
        ports:
            - '5438:5432'
        volumes:
            - ./itemdb/config:/docker-entrypoint-initdb.d/
    cart-api:
        image: meaty/cartapi
        container_name: cartapi
        restart: always
        build:
            context: ./cartservice
            dockerfile: Dockerfile
        environment: 
            - REDIS_HOST=cart-redis-db
            - REDIS_PORT=6379
        ports: 
            - "8081:8080"
        depends_on: 
            - cart-redis-db
            - item-api
    cart-redis-db:
        image: redis:alpine
        ports: 
            - 6379:6379
