version: '3'

services: 
    item-api:
        image: meaty/itemservice
        container_name: itemapi
        restart: always
        build:
            context: ./itemservice
            dockerfile: Dockerfile
        environment: 
            - DSN=host=postgres user=${APP_DB_USER} password=${APP_DB_PASS} dbname=${APP_DB_NAME} port=${APP_DB_PORT} sslmode=disable
            - PORT=:${API_SERVICE_PORT}
        ports: 
            - "8080:${API_SERVICE_PORT}"
        depends_on: 
            - postgres
    postgres:
        image: postgres:latest
        restart: always
        environment: 
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - APP_DB_USER=${APP_DB_USER}
            - APP_DB_PASS=${APP_DB_PASS}
            - APP_DB_NAME=${APP_DB_NAME}
        ports:
            - '5438:${APP_DB_PORT}'
        volumes:
            - ./itemdb/config:/docker-entrypoint-initdb.d/
    cart-api:
        image: meaty/cartapi
        container_name: cartapi
        restart: always
        build:
            context: ./cartservice
            dockerfile: Dockerfile
        environment: 
            - REDIS_HOST=cart-redis-db
            - REDIS_PORT=${REDIS_PORT}
            - PORT=:${API_SERVICE_PORT}
        ports: 
            - "8081:${API_SERVICE_PORT}"
        depends_on: 
            - cart-redis-db
            - item-api
    cart-redis-db:
        image: redis:alpine
        ports: 
            - 6379:${REDIS_PORT}
