version: '3'

services: 
    nginx-data:
        build:
            context: ./nginx
            dockerfile: Dockerfile
    gateway:
        image: seges/nginx-consul:1.9.0
        container_name: gateway
        volumes_from: 
            - nginx-data
        ports: 
            - 8080:80
    user-db:
        image: postgres:13.3
        restart: always
        container_name: user-db
        environment: 
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - APP_DB_USER=${APP_DB_USER}
            - APP_DB_PASS=${APP_DB_PASS}
            - APP_DB_NAME=${USER_DB_NAME}
        ports:
            - '5439:${APP_DB_PORT}'
        volumes:
            - ./userdb/config:/docker-entrypoint-initdb.d/
            - ./userdb/data:/var/lib/postgresql/data
        depends_on: 
    user-api:
        image: connect/userservice
        build: 
            context: ./userservice
            dockerfile: Dockerfile
        environment: 
            - DSN=host=user-db user=${APP_DB_USER} password=${APP_DB_PASS} dbname=${USER_DB_NAME} port=${APP_DB_PORT} sslmode=disable
            - PORT=:${API_SERVICE_PORT}
            - SECRET_KEY=${SECRET_KEY}
            # - CONSUL_HTTP_ADDR=consul:8500 
        ports: 
            - ${API_SERVICE_PORT}
        restart: always
        depends_on: 
            - user-db
